version: '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    networks:
      - domjudge-network
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=<rootpw>
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=<djpw>
      - MYSQL_DATABASE=domjudge
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  domserver:
    container_name: domserver
    image: domjudge/domserver:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - domserver_data:/opt/domjudge/domserver/etc
    networks:
      - domjudge-network
    ports:
      - 80:80
    depends_on:
      - mariadb
    environment:
      - CONTAINER_TIMEZONE=Asia/Tehran
      - MYSQL_HOST=mariadb
      - FPM_MAX_CHILDREN=70
      - MYSQL_ROOT_PASSWORD=<rootpw>
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=<djpw>
      - MYSQL_DATABASE=domjudge

networks:
  domjudge-network:
   name: domjudge-network

volumes:
  mariadb_data:
  domserver_data: